"""
Local HTTP API server for web app integration.

Security model
--------------
* Bound to 127.0.0.1 only (never reachable from LAN). The Host header is
  validated on every request, so DNS-rebinding pages cannot reach the
  API even when auth is disabled.
* Every protected endpoint requires `Authorization: Bearer <token>` where
  <token> is a random 256-bit value generated at startup and written to
  ~/.orizon-call/token (created with mode 0600). The companion web app
  reads that file (same machine) and includes it in every request.
  GET /events also accepts `?token=<token>` because the browser
  EventSource API cannot send custom headers.
* CORS: by default only loopback Origins are allowed. A specific origin
  can be added via --cors-origin (e.g. https://app.orizon.com). Wildcard
  CORS is not used: combined with the localhost listener + a hijackable
  browser session it would be a CSRF + exfiltration vector.
* Private Network Access: a public https web app calling 127.0.0.1 gets a
  Chrome preflight carrying `Access-Control-Request-Private-Network: true`;
  the preflight answer includes `Access-Control-Allow-Private-Network:
  true` (only for an allowed Origin) so the call is not blocked.
* Every handler is wrapped: an unexpected exception yields a JSON 500 and
  a log entry instead of a traceback on stderr and a dropped connection.

Endpoints
---------
Unprotected (no auth, useful for the web app to discover the server):
  GET  /health        → {"ok": true}
  OPTIONS *           → CORS preflight

Protected (require token):
  GET  /status        → snapshot of recorder state
  GET  /events        → SSE stream of status updates (header or ?token=)
  GET  /files         → list of recordings in the output dir
  GET  /files/<name>  → download a single recording (byte ranges honoured)
  HEAD                → supported on every GET endpoint
  POST /start         → begin recording (409 unless idle)
  POST /stop          → stop recording (409 unless recording/paused)
  POST /pause         → pause
  POST /resume        → resume
  POST /mute          → mute mic
  POST /unmute        → unmute mic
  POST /quit          → exit the app
"""

import json
import os
import re
import secrets
import socket
import stat
import threading
import urllib.parse
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from socketserver import ThreadingMixIn
from typing import TYPE_CHECKING, Optional

from orizon_logging import get_logger

if TYPE_CHECKING:
    from floating_widget import FloatingRecorderWidget

log = get_logger("api")

MAX_SSE_CONNECTIONS = 16


# ---------- Auth token ----------

def _token_path() -> Path:
    base = Path.home() / ".orizon-call"
    base.mkdir(parents=True, exist_ok=True)
    return base / "token"


def issue_token() -> str:
    """Generate a fresh token and persist it. The file is created with
    mode 0600 from the start — no window where it is world-readable."""
    token = secrets.token_urlsafe(32)
    path = _token_path()
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.write(fd, token.encode("utf-8"))
    finally:
        os.close(fd)
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # pre-existing files too
    except OSError:
        # Windows: chmod is a no-op; ACLs do the work.
        pass
    return token


def _token_matches(candidate: str, expected: str) -> bool:
    try:
        return secrets.compare_digest(
            candidate.encode("utf-8", errors="replace"),
            expected.encode("utf-8"),
        )
    except Exception:
        return False


# ---------- Server ----------

class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True


class RecorderAPIHandler(BaseHTTPRequestHandler):

    widget: "Optional[FloatingRecorderWidget]" = None
    output_dir: Optional[Path] = None
    auth_token: Optional[str] = None  # None = auth disabled
    cors_allowed_origin: Optional[str] = None  # extra origin beyond loopback

    _sse_clients = 0
    _sse_lock = threading.Lock()
    _response_started = False  # set once a status line went out (per request)

    # Errors generated by http.server itself (501 unsupported method, 400
    # bad request line, 414/431) use the documented JSON shape too: see
    # send_error below (the stdlib template would break on messages that
    # contain quotes, e.g. "Unsupported method ('PU\"T')").
    error_content_type = "application/json"

    # Characters never allowed in a download name: control chars (header
    # injection), quotes (break Content-Disposition), path separators.
    _UNSAFE_NAME_RE = re.compile(r'[\x00-\x1f\x7f"\\/]')
    _RANGE_RE = re.compile(r"\s*bytes=(\d{0,18})-(\d{0,18})\s*")  # bounded: int() must never blow up
    _HEADER_LIST_RE = re.compile(r"^[A-Za-z0-9\-_, ]+$")

    # Socket timeout (seconds): a client that stops reading/writing for
    # this long (half-open connection, suspended tab) releases its handler
    # thread instead of pinning it forever. SSE keeps writing every second,
    # so a healthy stream never trips it.
    timeout = 120

    # How long browsers may cache a CORS preflight answer.
    PREFLIGHT_MAX_AGE = 600

    # Endpoints that do NOT require auth.
    PUBLIC_PATHS = {"/health"}

    _TOKEN_RE = re.compile(r"(token=)[^&\s\"]+")

    def log_message(self, format, *args):
        # Suppress default stderr access log; the logger is enough.
        # Redact query-string tokens (?token=... on /events) — the debug
        # log must never persist the bearer secret.
        message = format % args
        log.debug(self._TOKEN_RE.sub(r"\1<redacted>", message))

    def _redacted_path(self) -> str:
        return self._TOKEN_RE.sub(r"\1<redacted>", self.path or "")

    def version_string(self) -> str:
        # Don't advertise the interpreter version in every response.
        return "OrizonCall"

    def send_response(self, code, message=None):
        self._response_started = True
        super().send_response(code, message)

    def send_error(self, code, message=None, explain=None):
        """JSON body for the errors http.server raises on its own (bad
        request line, unsupported method, oversized headers...), always
        valid JSON whatever the message contains."""
        try:
            short, _long = self.responses[code]
        except KeyError:
            short = "???"
        if message is None:
            message = short
        self.log_error("code %d, message %s", code, message)
        self.send_response(code, short)
        self.send_header("Connection", "close")
        body = None
        if code >= 200 and code not in (204, 205, 304) and self.command != "HEAD":
            body = json.dumps({"error": message, "code": code}).encode("utf-8")
            self.send_header("Content-Type", self.error_content_type)
            self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            try:
                self.wfile.write(body)
            except ConnectionError:
                pass

    # ---------- Host validation (DNS rebinding) ----------

    def _host_allowed(self) -> bool:
        host = (self.headers.get("Host") or "").strip()
        if not host:
            return True  # HTTP/1.0 probes (our own single-instance check)
        # Strip port; tolerate bracketed IPv6.
        if host.startswith("["):
            hostname = host.partition("]")[0].lstrip("[")
        else:
            hostname = host.rsplit(":", 1)[0] if ":" in host else host
        return hostname.lower() in ("localhost", "127.0.0.1", "::1")

    # ---------- CORS ----------

    def _origin_allowed(self, origin: Optional[str]) -> bool:
        if not origin:
            return True

        if RecorderAPIHandler.cors_allowed_origin and origin == RecorderAPIHandler.cors_allowed_origin:
            return True

        try:
            parsed = urllib.parse.urlparse(origin)

            if parsed.scheme not in ("http", "https"):
                return False

            if parsed.username or parsed.password:
                return False

            host = parsed.hostname or ""
            if host not in ("localhost", "127.0.0.1", "::1"):
                return False

            expected_host = f"[{host}]" if ":" in host else host
            expected_origin = f"{parsed.scheme}://{expected_host}"

            port = parsed.port
            if port:
                expected_origin += f":{port}"

            return origin == expected_origin
        except ValueError:
            return False

    def _set_cors_headers(self, preflight: bool = False) -> None:
        origin = self.headers.get("Origin")
        allowed = bool(origin) and self._origin_allowed(origin)
        if allowed:
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")
        self.send_header("Access-Control-Allow-Methods", "GET, HEAD, POST, OPTIONS")
        # Reflect the headers the browser asks for (only for an allowed
        # origin, only plain header-name characters) so a web app that
        # adds e.g. X-Requested-With is not blocked by the preflight.
        requested = (self.headers.get("Access-Control-Request-Headers") or "").strip()
        if preflight and allowed and requested and self._HEADER_LIST_RE.match(requested):
            self.send_header("Access-Control-Allow-Headers", requested)
        else:
            self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        # Let cross-origin scripts read the download metadata.
        self.send_header("Access-Control-Expose-Headers",
                         "Content-Disposition, Content-Length, Content-Range, Accept-Ranges")
        if preflight:
            self.send_header("Access-Control-Max-Age", str(self.PREFLIGHT_MAX_AGE))
            # Chrome Private Network Access: a public site reaching a
            # loopback address must be explicitly allowed in the preflight.
            pna = (self.headers.get("Access-Control-Request-Private-Network") or "").strip().lower()
            if allowed and pna == "true":
                self.send_header("Access-Control-Allow-Private-Network", "true")

    def _json_response(self, status: int, data: dict,
                       extra_headers: Optional[dict] = None) -> None:
        if status >= 400 and "error" in data:
            data = dict(data)
            data.setdefault("code", status)  # same shape as stdlib-level errors
        body = json.dumps(data, default=str).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        for name, value in (extra_headers or {}).items():
            self.send_header(name, value)
        self._set_cors_headers()
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command == "HEAD":
            return
        try:
            self.wfile.write(body)
        except ConnectionError:
            pass  # client went away (BrokenPipe/Reset/Aborted on Windows)

    def do_OPTIONS(self):  # noqa: N802 — http.server API
        self.send_response(204)
        self._set_cors_headers(preflight=True)
        self.end_headers()

    # ---------- Auth gate ----------

    def _authorize(self, path: str, query: dict) -> bool:
        if not self._host_allowed():
            self._json_response(403, {"error": "invalid host"})
            return False
        if path in self.PUBLIC_PATHS or RecorderAPIHandler.auth_token is None:
            return True
        header = self.headers.get("Authorization", "")
        scheme, _, credentials = header.strip().partition(" ")
        token = ""
        if scheme.lower() == "bearer":  # RFC 7235: scheme is case-insensitive
            token = credentials.strip()
        elif path == "/events":
            # EventSource cannot send custom headers — allow ?token= for
            # the SSE endpoint only.
            values = query.get("token") or []
            token = values[0] if values else ""
        if not token:
            self._json_response(401, {"error": "missing bearer token"},
                                extra_headers={"WWW-Authenticate": 'Bearer realm="orizon-call"'})
            return False
        if not _token_matches(token, RecorderAPIHandler.auth_token):
            self._json_response(403, {"error": "invalid token"})
            return False
        return True

    # ---------- Routing ----------

    def _guarded(self, handler) -> None:
        """Run a request handler; turn an unexpected exception into a JSON
        500 (only when no response has been started yet — never inject a
        status line into a stream or download already in progress) plus a
        log entry with the bearer secret redacted."""
        self._response_started = False
        try:
            handler()
        except (ConnectionError, socket.timeout):
            pass  # client went away — nothing to answer
        except Exception:
            log.exception("Unhandled error while serving %s %s", self.command, self._redacted_path())
            if not self._response_started:
                try:
                    self._json_response(500, {"error": "internal error"})
                except Exception:
                    pass

    def do_GET(self):  # noqa: N802
        self._guarded(self._do_get)

    def do_HEAD(self):  # noqa: N802
        # Same routing/auth as GET; bodies are suppressed by the writers.
        self._guarded(self._do_get)

    def do_POST(self):  # noqa: N802
        self._guarded(self._do_post)

    def _do_get(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        query = urllib.parse.parse_qs(parsed.query)
        if not self._authorize(path, query):
            return

        if path == "/status":
            self._handle_status()
        elif path == "/health":
            self._json_response(200, {"ok": True})
        elif path == "/events":
            self._handle_events_sse()
        elif path == "/files":
            self._handle_files_list()
        elif path.startswith("/files/"):
            filename = urllib.parse.unquote(path[len("/files/"):])
            self._handle_file_download(filename)
        else:
            self._json_response(404, {"error": "not found"})

    def _do_post(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        self._drain_request_body()
        if not self._authorize(path, urllib.parse.parse_qs(parsed.query)):
            return

        if path == "/start":
            self._invoke_widget_slot("api_start", started="starting", require_state="idle")
        elif path == "/stop":
            self._handle_stop_with_meta()
        elif path == "/pause":
            self._invoke_widget_slot("api_pause", started="pausing", require_state="recording")
        elif path == "/resume":
            self._invoke_widget_slot("api_resume", started="resuming", require_state="paused")
        elif path == "/mute":
            self._invoke_widget_slot("api_mute", started="muted")
        elif path == "/unmute":
            self._invoke_widget_slot("api_unmute", started="unmuted")
        elif path == "/quit":
            self._invoke_widget_slot("api_quit", started="quitting")
        else:
            self._json_response(404, {"error": "not found"})

    def _drain_request_body(self) -> None:
        """Read and discard any request body so the response isn't sent
        while unread data sits in the socket buffer."""
        try:
            length = int(self.headers.get("Content-Length", 0) or 0)
        except ValueError:
            length = 0
        remaining = min(length, 1 << 20)  # never read more than 1 MB
        while remaining > 0:
            chunk = self.rfile.read(min(remaining, 65536))
            if not chunk:
                break
            remaining -= len(chunk)

    # ---------- Slot invocation helpers ----------

    def _widget(self) -> "Optional[FloatingRecorderWidget]":
        return RecorderAPIHandler.widget

    def _invoke_widget_slot(
        self,
        slot_name: str,
        started: str,
        require_state: Optional[str] = None,
    ) -> None:
        w = self._widget()
        if not w:
            self._json_response(503, {"error": "recorder not ready"})
            return
        if require_state is not None and w.recorder_state_name() != require_state:
            self._json_response(409, {"error": f"requires state {require_state}",
                                       "state": w.recorder_state_name()})
            return
        from PyQt6.QtCore import QMetaObject, Qt as QtConst
        QMetaObject.invokeMethod(w, slot_name, QtConst.ConnectionType.QueuedConnection)
        self._json_response(200, {"status": started})

    def _handle_stop_with_meta(self) -> None:
        w = self._widget()
        if not w:
            self._json_response(503, {"error": "recorder not ready"})
            return
        if w.recorder_state_name() not in ("recording", "paused"):
            self._json_response(409, {"error": "not recording",
                                       "state": w.recorder_state_name()})
            return
        status = w.recorder_status()
        from PyQt6.QtCore import QMetaObject, Qt as QtConst
        QMetaObject.invokeMethod(w, "api_stop", QtConst.ConnectionType.QueuedConnection)
        self._json_response(200, {
            "status": "stopping",
            "elapsed": status["elapsed"],
            "output_path": status["output_path"],
        })

    # ---------- Status ----------

    def _handle_status(self) -> None:
        w = self._widget()
        if not w:
            self._json_response(503, {"error": "recorder not ready"})
            return
        self._json_response(200, w.recorder_status())

    # ---------- SSE Events ----------

    def _handle_events_sse(self) -> None:
        w = self._widget()
        if not w:
            self._json_response(503, {"error": "recorder not ready"})
            return

        if self.command == "HEAD":
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self._set_cors_headers()
            self.end_headers()
            return

        with RecorderAPIHandler._sse_lock:
            if RecorderAPIHandler._sse_clients >= MAX_SSE_CONNECTIONS:
                self._json_response(503, {"error": "too many event streams"})
                return
            RecorderAPIHandler._sse_clients += 1

        try:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.send_header("Connection", "keep-alive")
            self._set_cors_headers()
            self.end_headers()

            # Tell EventSource how quickly to reconnect after the app
            # restarts (default browser back-off can be several seconds).
            try:
                self.wfile.write(b"retry: 2000\n\n")
            except OSError:
                return

            last_state: Optional[str] = None
            # Change-sequence handshake: the sequence read *before* each
            # snapshot is handed back to the wait, so a transition that
            # lands between snapshot and wait wakes us at once instead of
            # surfacing at the next 1 s tick.
            since = w.wait_for_status_change(timeout=0.0, since=None)
            while True:
                try:
                    status = w.recorder_status()
                    current_state = status.get("state")
                    data_line = json.dumps(status, default=str)
                    self.wfile.write(f"data: {data_line}\n\n".encode())
                    if current_state != last_state and last_state is not None:
                        self.wfile.write(f"event: statechange\ndata: {data_line}\n\n".encode())
                    last_state = current_state
                    self.wfile.flush()
                    since = w.wait_for_status_change(timeout=1.0, since=since)
                except (BrokenPipeError, ConnectionResetError, OSError):
                    break
        finally:
            with RecorderAPIHandler._sse_lock:
                RecorderAPIHandler._sse_clients -= 1

    # ---------- Files ----------

    def _get_recordings_dir(self) -> Path:
        # Prefer the widget's live folder (follows the settings dialog);
        # fall back to the startup value, then to ~/Downloads.
        w = RecorderAPIHandler.widget
        recordings_dir = getattr(w, "recordings_dir", None)
        if recordings_dir is not None:
            try:
                return recordings_dir()
            except Exception:
                pass
        if RecorderAPIHandler.output_dir:
            return RecorderAPIHandler.output_dir
        return Path.home() / "Downloads"

    def _handle_files_list(self) -> None:
        rec_dir = self._get_recordings_dir()
        files = []
        for ext in ("*.wav", "*.flac", "*.mp3"):
            try:
                matches = list(rec_dir.glob(f"recording_{ext}"))
            except OSError as e:
                # Folder missing / unreadable (unmounted drive, permissions):
                # an empty list is the truthful answer, not a 500.
                log.warning("Cannot list recordings in %s: %s", rec_dir, e)
                matches = []
            for f in matches:
                try:
                    s = f.stat()
                except OSError:
                    continue
                if not f.is_file():
                    continue
                files.append({
                    "name": f.name,
                    "size": s.st_size,
                    "modified": s.st_mtime,
                    "path": str(f),
                })
        # Most recent first across ALL extensions, then cap.
        files.sort(key=lambda item: item["modified"], reverse=True)
        self._json_response(200, {"files": files[:50]})

    def _handle_file_download(self, filename: str) -> None:
        if (not filename or ".." in filename
                or self._UNSAFE_NAME_RE.search(filename)):
            self._json_response(400, {"error": "invalid filename"})
            return
        # Access policy first: don't leak existence of non-recording files.
        if not filename.startswith("recording_"):
            self._json_response(403, {"error": "access denied"})
            return
        rec_dir = self._get_recordings_dir().resolve()
        try:
            filepath = (rec_dir / filename).resolve()
        except (OSError, ValueError):
            self._json_response(400, {"error": "invalid path"})
            return
        if not filepath.is_relative_to(rec_dir):
            self._json_response(403, {"error": "access denied"})
            return
        if not filepath.exists() or not filepath.is_file():
            self._json_response(404, {"error": "file not found"})
            return

        # Open before committing to a status line: a file locked by the
        # writer (Windows) or vanished must be a clean 404, not a broken 200.
        try:
            fh = open(filepath, "rb")
        except OSError:
            self._json_response(404, {"error": "file not found"})
            return
        with fh:
            try:
                file_size = os.fstat(fh.fileno()).st_size
            except OSError:
                file_size = filepath.stat().st_size

            # Single byte range (RFC 7233): what <audio> elements and
            # resumable downloads need. Multi-range stays unsupported.
            start, end, status = 0, file_size - 1, 200
            range_header = self.headers.get("Range")
            match = self._RANGE_RE.fullmatch(range_header) if range_header else None
            if match and file_size > 0:
                first, last = match.groups()
                if first == "" and last == "":
                    pass  # malformed → ignore, serve everything
                else:
                    if first == "":
                        start = max(file_size - int(last), 0)
                    else:
                        start = int(first)
                        end = min(int(last), file_size - 1) if last else file_size - 1
                    if start > end or start >= file_size:
                        self.send_response(416)
                        self.send_header("Content-Range", f"bytes */{file_size}")
                        self._set_cors_headers()
                        self.send_header("Content-Length", "0")
                        self.end_headers()
                        return
                    status = 206
            length = end - start + 1 if file_size > 0 else 0

            ext = filepath.suffix.lower()
            content_types = {".wav": "audio/wav", ".flac": "audio/flac", ".mp3": "audio/mpeg"}
            content_type = content_types.get(ext, "application/octet-stream")
            ascii_name = filename.encode("ascii", "replace").decode("ascii")
            utf8_name = urllib.parse.quote(filename, safe="")

            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Disposition",
                             f'attachment; filename="{ascii_name}"; filename*=UTF-8\'\'{utf8_name}')
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Content-Length", str(length))
            if status == 206:
                self.send_header("Content-Range", f"bytes {start}-{end}/{file_size}")
            self._set_cors_headers()
            self.end_headers()
            if self.command == "HEAD":
                return

            fh.seek(start)
            remaining = length
            while remaining > 0:
                chunk = fh.read(min(65536, remaining))
                if not chunk:
                    break
                remaining -= len(chunk)
                try:
                    self.wfile.write(chunk)
                except ConnectionError:
                    break


def normalize_origin(value: Optional[str]) -> Optional[str]:
    """Turn what a user typed for --cors-origin into the serialized origin
    browsers actually send (lowercase scheme+host, default port dropped,
    no path/trailing slash). Returns None (and logs) for non-http(s) input
    — an exact-string compare would silently disable the whole feature."""
    if not value or not value.strip():
        return None
    raw = value.strip()
    try:
        parts = urllib.parse.urlsplit(raw)
        scheme = parts.scheme.lower()
        host = parts.hostname
        port = parts.port
    except ValueError as e:
        log.error("--cors-origin %r is not a valid origin (%s); ignoring.", raw, e)
        return None
    if scheme not in ("http", "https") or not host:
        log.error("--cors-origin %r is not an http(s) origin; ignoring.", raw)
        return None
    host = f"[{host}]" if ":" in host else host.lower()
    default_port = (scheme == "http" and port == 80) or (scheme == "https" and port == 443)
    origin = f"{scheme}://{host}" + (f":{port}" if port and not default_port else "")
    if origin != raw:
        log.info("--cors-origin %r normalized to %s", raw, origin)
    return origin


def start_api_server(
    widget: "FloatingRecorderWidget",
    port: int = 19876,
    output_dir: Optional[Path] = None,
    cors_origin: Optional[str] = None,
    require_auth: bool = True,
    bound_socket: Optional[socket.socket] = None,
) -> Optional[ThreadedHTTPServer]:
    """Start the threaded API server. Returns the server or None on failure.

    When ``bound_socket`` is provided (the single-instance probe socket),
    the server adopts it instead of binding again — no close/rebind race.
    """
    RecorderAPIHandler.widget = widget
    RecorderAPIHandler.output_dir = output_dir
    RecorderAPIHandler.cors_allowed_origin = normalize_origin(cors_origin)
    if require_auth:
        RecorderAPIHandler.auth_token = issue_token()
        # The token itself must never hit the logs.
        log.info("Auth token written to %s", _token_path())
    else:
        RecorderAPIHandler.auth_token = None
        log.warning("API auth DISABLED (--no-auth). Anyone with browser access "
                    "to localhost can control the recorder.")

    try:
        if bound_socket is not None:
            server = ThreadedHTTPServer(
                ("127.0.0.1", port), RecorderAPIHandler, bind_and_activate=False)
            server.socket = bound_socket
            server.server_address = bound_socket.getsockname()
            server.server_activate()
        else:
            server = ThreadedHTTPServer(("127.0.0.1", port), RecorderAPIHandler)
    except OSError as e:
        log.error("Cannot bind to port %d: %s", port, e)
        return None

    thread = threading.Thread(target=server.serve_forever, daemon=True, name="api-server")
    thread.start()
    log.info("API listening on http://127.0.0.1:%d", port)
    return server


def stop_api_server(server: Optional[ThreadedHTTPServer]) -> None:
    """Stop serve_forever() and release the listening socket. Safe to call
    with None. Handler threads are daemons: an open SSE stream does not
    delay process exit."""
    if server is None:
        return
    try:
        server.shutdown()
    except Exception as e:
        log.debug("API shutdown: %s", e)
    try:
        server.server_close()
    except Exception as e:
        log.debug("API server_close: %s", e)
